### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by khomtali** [redi-js-teachers/js_sprint_2020_final_project_khomtali#15]
Create first version of app design with [figma.com](figma.com)

**Comment by khomtali** [comment]
Because of my very simple design Figma seemed me to do double work, that's why I've already added some general style to my page while adding of React Router, in #16.

**Comment by BTBTravis** [comment]
I think the point of working with something like figma at this stage is to elevate your css skills. If you are interested in that I would suggest finding few website interfaces you think are good matches for you app and trying to remix them into your own design.

**Comment by BTBTravis** [comment]
I dig the Instagram pic. 👍 Perhaps design stuff can wait until you want to focus on that more.

**Comment by khomtali** [comment]
I'd put it aside till the next time...
