### ISSUE TITLE
Training plans DBs

### ISSUE THREAD

**Issue by khomtali** [redi-js-teachers/js_sprint_2020_final_project_khomtali#17]
Hey @BTBTravis
Could you please tell me in what format I should provide you training plans databases? Maybe you know any resources which can help me to provide you information in the most appropriate form?

I've made today two excel tables: one with different types of training and the second with training plans. I have only one plan in this table - 5 km race as goal, 1st level for newers - but later I'll add others as well.

**Comment by BTBTravis** [comment]
hmmm. could you attach what you have so I can get an idea?

**Comment by khomtali** [comment]
ja, sure:
[ReDI-Run-App DB.xlsx](https://github.com/redi-js-teachers/js_sprint_2020_final_project_khomtali/files/4794067/ReDI-Run-App.DB.xlsx)

**Comment by BTBTravis** [comment]
Alright interesting. I think we should have these somewhere you can easily edit/tweak them and add more. Off the bat I'm thinking air table would be a good fit. I don't have the vision exactly how how you are using them but I think airtable would be a good fit. 

I like a single base in airtable called training plans. then two tables one with the tags and one the workouts. Then this data is queried via the airtable api from the python backend and returned the browser. Air table put unique ids on rows so we can can easily assign users trainings and such as well.

**Comment by BTBTravis** [comment]
I can move the data from excel to air table and get that started if you like?

**Comment by khomtali** [comment]
yeah, sounds pretty good!

You can move only two big tables. They match together by type of trainings and a number of it. First one is just a bank of different training types.
The table with long descriptions is only for me to add these descriptions to the page.

**Comment by khomtali** [comment]
added 6 training plans to air table - 3 levels of 5km and 3 of 10km

**Comment by BTBTravis** [comment]
Seems we have a training data off the ground. Please create future issues regarding backend features on the backen [repo](https://github.com/BTBTravis/redi-run-api) 👍
