### ISSUE TITLE
My Profile tab

### ISSUE THREAD

**Issue by khomtali** [redi-js-teachers/js_sprint_2020_final_project_khomtali#18]
I would like to add to this tab:
- fields with opportunity to change
  - nickname
  - age (or date of birth? then user is not needed to update age)
  - resting heart rate
- button to delete an account

@BTBTravis could you build an endpoint which allows to delete user account?

**Comment by khomtali** [comment]
So, I also want to change `nickname` and `name`. Or is it already possible like `age`? I can't' reach the server again to check it.

**Comment by BTBTravis** [comment]
I think we have some nickname / name related stuff from the auth0 responce if you want to use that. Or we can add it as well. Let me check.

**Comment by BTBTravis** [comment]
Yep this info is returned from auth0 on the client side:
```
﻿email: "test@travisshears.com"
​​
email_verified: false
​​
name: "test@travisshears.com"
​​
nickname: "test"
​​
picture: "https://s.gravatar.com/avatar/2d3e52adbf5283a41dd8d8a546e8fe86?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fte.png"
​​
sub: "auth0|5eea4dfbb8a6590019e59ea7"
​​
updated_at: "2020-06-17T17:08:12.223Z"
```
perhaps we could use some of it?

coming from src/configurations/auth.js

**Comment by BTBTravis** [comment]
ahh delete account is interesting deleting from backend easy. I can provide an endpoint for that. Not sure about auth0 though.

**Comment by BTBTravis** [comment]
I created separate issue for deleting users #26

**Comment by BTBTravis** [comment]
good work
