### ISSUE TITLE
Init React App

### ISSUE THREAD

**Issue by BTBTravis** [redi-js-teachers/js_sprint_2020_final_project_khomtali#2]
From the sound of it and if you agree we'll be doing this final project as a single page app (SAP) written in React. Please create a PR that does the following:

- [x] delete existing template HTML, JS, and CSS content from this repo, one commit for this
- [x] then add the default create react app output to this project
- [x] update the package.json with your information
  - `"author": "Test Man <testman@gmail.com>"`
  - `"name": "your-app-name",`
  - `"version": "0.0.1",`
  - `"description": "lil about your app",`

## Adding react

We want the top directory of this repo to contain the package.json from the create react app output. One way to do this would be to create-react-app into a temp folder and move the files into the root dir manually. Take care not to overwrite the README.md file of your repo. If you want to also have the create react app README.md please put it in the docs folder under `React_README.md` and link to it in your main README.md

**Comment by khomtali** [comment]
Thank you for the detailed description.
Done, see #4

**Comment by BTBTravis** [comment]
done
