### ISSUE TITLE
Add loading

### ISSUE THREAD

**Issue by khomtali** [redi-js-teachers/js_sprint_2020_final_project_khomtali#22]
@MrTim :
> When user is logged in and you refresh the page there is a delay when auth server checks that user is logged in or not. During that time you need to lock the page and show a spinner or progressbar. Because at the moment I see parts of layout which I should not see, and layout it "jumping".

**Comment by BTBTravis** [comment]
Yeah I agree. Loading state would be good idea.

**Comment by khomtali** [comment]
done in #28

**Comment by khomtali** [comment]
@MrTim:
> You can implement this behavior with context. Since you already have this user context you can have loading state there. As well you can have a useReducer hook.
Can recommend you to look at this article: https://kentcdodds.com/blog/how-to-use-react-context-effectively

- [ ] create a new branch `loading_state_v2`
- [ ] change loading state tracking using `useReducer`
- [ ] compare 2 branches in PR

**Comment by khomtali** [comment]
reopened (see comment above)

**Comment by khomtali** [comment]
to redo the tracking of loading state I'll open a new issue
