### ISSUE TITLE
Heart Rate Zone Caculator, (no backend)

### ISSUE THREAD

**Issue by BTBTravis** [redi-js-teachers/js_sprint_2020_final_project_khomtali#3]
Since the landing page with feature both the signup form and heart rate zone calculator lets start with the heart rate zone calculator. For now lets not worry about saving the results to the backend but just taking the user input and converting it to the zone representation. 

This issues depends on #2 .

**Comment by khomtali** [comment]
Could you please check my first attempt in #6 🙃

**Comment by BTBTravis** [comment]
Good to go 👍
