### ISSUE TITLE
 Running related APIs

### ISSUE THREAD

**Issue by khomtali** [redi-js-teachers/js_sprint_2020_final_project_khomtali#5]
Here I would like to collect information about different APIs related to running / training topic. And to discuss which one is the best for my project (for training plan configurator) or has interesting functions and I could use it later to do my app more functional.

**Comment by khomtali** [comment]
- https://www.runningahead.com/ seems that I can't use any of it. I don't see API, and there is a manual creation of trainings plan, not like prepared plans or from any other resources
- https://dev.fitbit.com/getting-started/ only app development for FitBit OS devices. I don't have one
- https://api.smashrun.com/ works only with information, which is already exist in SmashRun user's account. So there are no any prescribed trainings plans. Seems like Strava, but actually not so popular

**Comment by khomtali** [comment]
https://2peak.com/api/why.php is pretty much the same what I would like to build. But it is already done 🙃 and in a very good (even the best I can imagine) way as I can see from their website. They have patented dynamic training plan calculation, wow. And they allow developers to connect with everything what they offer.
I'll try to get in contact with them to get API access for my app🤞

**Comment by khomtali** [comment]
https://developers.strava.com/ just to point it out once again here.
I know about Strava, but it would be the next level of my app. Someday. I hope😄

**Comment by khomtali** [comment]
I got the answer from 2PEAK with provided client_id and client_secret!

@BTBTravis could you please take a look on API documentation? If I understand it right, seems they already have OAuth2 service. In that case do we need both user authentications?
You are super high-speed, I haven't checked `signup-button` yet.

API documentation here: http://2peak.com/api/doc/index.html

**Comment by BTBTravis** [comment]
Hey @khomtali good work talking to 2PEAK.

1. It is not clear to me how you see your app integrating with 2PEAK. What is your vision?

2. Perhaps your app could be a much smaller home made version of 2PEAK offering users free training advice?

3. Maybe there is a very specific thing your app could do to help with training? It could be entirely based around a single statistic such as how often user executes on a plan to run. With features built around the single purpose help them stick to a running plan. Notifications.. Records..

**Comment by khomtali** [comment]
@BTBTravis good questions...

2PEAK has a perfect calculating function of training plans. And opportunity to recaltulate it in case of any new information - new training performed or change of goal. But I find it too complicated as it is now represented in their interface. I would like to build a simpler app for users, with that they will be not needed getting stuck in settings. Just make the plan, adjust it a bit may be by changing some dates and time of training.
There is only one way to use their API - as you mentioned, to make a smaller home made version of 2PEAK (which will furthermore become in 21 days paid). And to add some specific things as you suggested or as I wrote previously for example - to download a plan for google / apple calender. Notifications are also good idea, but in web version of app (not mobile I mean) how to send it? I don't like the way of e-mail notifications.

Or... not to deal with 2PEAK at all, to make my own simple databases of training plans and that's it. :)
Sorry that we're once again back to discuss concept. Both ways have disadvantages, and actually I'm not sure that I can realise any one of them. 😬😳
Could you please share your opinion which would be better to choose?

**Comment by MrTim** [comment]
Hm..how I see it:
since there is not that many options for you to choose api and since it's not require to be super dynamic in configuring the plans why not to create 2-3 variations of a training plans?
I thinks you(we) can come up with some more or less configurable idea and create a bd table with some data which could be adjusted based on - timeframe, length and age for instance.
This should not be very complicatied right from the start. It's the other way around usually - start super simple and then build more complex thing. And if later you would feel that you need some api => probably it's worth to pay for one.

This is some thoughts from my side :)

**Comment by khomtali** [comment]
Think I can close this issue. I come back to it when I will be ready to improve my app.

**Comment by khomtali** [comment]
Think I can close this issue. I come back to it when I will be ready to improve my app.

**Comment by BTBTravis** [comment]
Great work @MrTim  and @khomtali
