### ISSUE TITLE
Save first user data

### ISSUE THREAD

**Issue by BTBTravis** [redi-js-teachers/js_sprint_2020_final_project_khomtali#9]
Hey @khomtali the backend is ready to save some user data. What is the first thing you want to save? I'll create the backend endpoint. 

## backend thus far

- `/client-info` -  GET -  for auth config
- `/user` - GET - to get an existing user / create a new one

We'll better document these endpoints in the future.

**Comment by khomtali** [comment]
@BTBTravis I've created one more user. :)
First data I would like to save are user age, resting heart rate and of course his calculated heart rate zones.

**Comment by BTBTravis** [comment]
Nice. Whats the shape of the data you want to save? Please provide a JSON example?

I'd like to see the structure so I an implement the backend endpoint. 

If the user only has one age, resting heart rate perhaps I can just extend the user object with these values and you can calculate resting heart rate zones on the frontend?

**Comment by BTBTravis** [comment]
Alright I've created extended the `/user` endpoint to support `PATCH` requests with the needed fields.

sound be something like this
```js
fetch("http://xxxxxx.com/api/run/v1/user", {
  "method": "PATCH",
  "headers": {
    "authorization": "Bearer xxxxxxxxxxxxxxxxxxxxxxx",
    "content-type": "application/json"
  },
  "body": {
    "id": "auth0|5ed93941a11c7f001a157fb9",
    "fields": {
      "age": 20
    }
  }
})
.then(response => {
  console.log(response);
})
.catch(err => {
  console.log(err);
});
```

also supports `resting_heart_rate` 

please integrate into your app and create a PR.

**Comment by BTBTravis** [comment]
I've added OpenAPI docs to the backend I build. https://btbtravis.gitlab.io/redi-run-backend

**Comment by BTBTravis** [comment]
> Alright I've created extended the `/user` endpoint to support `PATCH` requests with the needed fields.
> 
> sound be something like this
> 
> ```js
> fetch("http://xxxxxx.com/api/run/v1/user", {
>   "method": "PATCH",
>   "headers": {
>     "authorization": "Bearer xxxxxxxxxxxxxxxxxxxxxxx",
>     "content-type": "application/json"
>   },
>   "body": {
>     "id": "auth0|5ed93941a11c7f001a157fb9",
>     "fields": {
>       "age": 20
>     }
>   }
> })
> .then(response => {
>   console.log(response);
> })
> .catch(err => {
>   console.log(err);
> });
> ```
> 
> also supports `resting_heart_rate`
> 
> please integrate into your app and create a PR.

please refer to [docs](https://btbtravis.gitlab.io/redi-run-backend) as they are better source.
